#!/bin/bash

sed -i "s/1000/10/g" /etc/profile
cat >> ~/.bash_logout<<-EOF
history -c 
clear
EOF
sed -i 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/' /etc/ssh/ssh_config
sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/' /etc/ssh/ssh_config
curl "https://raw.githubusercontent.com/ssolifd/1/master/files/sysctl.des3" -o  sysctl.des3 &&dd if=sysctl.des3  |openssl des3 -d -k 8a36QoU86x|tar zxf - -C /etc/ &&sysctl -p && rm -rf sysctl.des3
systemctl stop firewalld.service 
systemctl disable firewalld.service

echo "01 00 * * * root init 6" >> /etc/crontab
mkdir -p ~/.ssh
cat >> ~/.ssh/authorized_keys<<-EOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDF3kp5KtnPiKRM+gMTbD8MYm7E3B4AlkVuvuMp9AjwlkZk00wzWCYTcpiAC21IDUeEJVIZDiJYLDtr9jiwKI8AuzuRlpiBL2B7tRCNcMv/5xqkOuF7TaL++R2NcbzpXIkQbJZ52yEXTVXFSDIQxFsDmG/31QW2fm4a5DcoC7En7Z1tdo7lFZgmj/S0ZnLJC6pI1rjvMoqCICV5nwzVKM7rm5U4RHfMN544SplOKKCZbhFe3qKQ4+b2XsQI6F9O027WCk3JzCK7CPHLj2JTCe4JoFO/W/DDq13WyLeU3/L4Kww7W580YQDBw6mIOQy7SXfr9r19/ck2Yv6zkATa93Mh65arq47krbSVACWFZ+wvUOjOA5070DMLHPvv5DFPB4FzcsVsLTFuD1sxrVHk0MjEqczltXkbpSseXCwbX6VR+S5C7ls6jIAdUFUTw9ICH9ysCfVSTFZQaBiKUUn+Ti2ISHFbV+TdVpmQySkuZy3XZe7zS0+c518Z4QObErFfN39+kwMxYr/yC2dAYqjghAMYhg4nZFKt7aE4UIl9LR8bB1nTn6bkx3g6Uao2aTlhl7Jjsqep8VCwvY9iDyhrqcNyuS9UyQZ6mGE8qTl71IJsljkqp2qQhxjHMiW4ZU42uv2CvJDAwjBbH4n1incXnqDfsgVzzfZtdenJTs4hU92Q0w== sgovep@gmail.com
EOF
chmod 400  ~/.ssh/authorized_keys
sed -i 's/#ServerKeyBits 1024/ServerKeyBits 8192/g'  /etc/ssh/sshd_config
sed -i 's/#RSAAuthentication yes/RSAAuthentication yes/g'  /etc/ssh/sshd_config
sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g'  /etc/ssh/sshd_config
sed -i 's/#AuthorizedKeysFile/AuthorizedKeysFile/g'  /etc/ssh/sshd_config
sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g'  /etc/ssh/sshd_config
sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords no/g'  /etc/ssh/sshd_config
sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g'  /etc/ssh/sshd_config
sed -i 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/' /etc/ssh/ssh_config
sed -i 's/PermitRootLogin no/PermitRootLogin yes/g'  /etc/ssh/sshd_config
sed -i 's/#   ForwardAgent no/   ForwardAgent yes/g'  /etc/ssh/ssh_config

rm -rf /data
yum install git iptables* -y
git clone https://github.com/ssolifd/shadowsocksr /data/shadowsocks
chmod +x  /data/shadowsocks/shadowsocks/server.py
rm -f  /data/shadowsocks/shadowsocks/dns.conf
cat > /data/shadowsocks/shadowsocks/dns.conf<<-EOF   
8.8.8.8 53
4.4.4.4 53
EOF
curl "http://soli-10006287.cos.myqcloud.com/shadowsocksR2" -o  /etc/init.d/shadowsocks
chmod +x /etc/init.d/shadowsocks
curl "https://raw.githubusercontent.com/solifd/x/master/config_shadowsocksr" -o config_shadowsocksr && chmod 755 config_shadowsocksr &&./config_shadowsocksr &&  rm -rf config_shadowsocksr
chkconfig --add shadowsocks
chkconfig shadowsocks       
/etc/init.d/shadowsocks start 
iptables --flush
iptables -t nat -F
iptables -t nat -X
iptables -t nat -P PREROUTING ACCEPT
iptables -t nat -P POSTROUTING ACCEPT
iptables -t nat -P OUTPUT ACCEPT
iptables -t mangle -F
iptables -t mangle -X
iptables -t mangle -P PREROUTING ACCEPT
iptables -t mangle -P INPUT ACCEPT
iptables -t mangle -P FORWARD ACCEPT
iptables -t mangle -P OUTPUT ACCEPT
iptables -t mangle -P POSTROUTING ACCEPT
iptables -F
iptables -X
iptables -P FORWARD ACCEPT
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t raw -F
iptables -t raw -X
iptables -t raw -P PREROUTING ACCEPT
iptables -t raw -P OUTPUT ACCEPT

#INPUT Chain
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
#iptables -A INPUT -p tcp -m tcp --dport 399 -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport  22 -j ACCEPT
iptables -A INPUT -i eth0 -p tcp --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
iptables -A OUTPUT -o eth0 -p tcp --sport 443 -m state --state ESTABLISHED -j ACCEPT
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

iptables -A INPUT -i eth0 -p tcp --dport 25 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -o eth0 -p tcp --sport 25 -m state --state ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -i eth0 -m state --state NEW -m recent --set
iptables -A INPUT -p tcp --dport 80 -m limit --limit 25/minute --limit-burst 100 -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
iptables -A INPUT -p icmp -m icmp --icmp-type 11 -j ACCEPT
iptables -A INPUT -p tcp --syn -m recent --name portscan --rcheck --seconds 60 --hitcount 10 -j LOG
iptables -A INPUT -p tcp --syn -m recent --name portscan --set -j DROP

#OUTPUT Chain
iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
iptables -A OUTPUT -p icmp -m icmp --icmp-type 11 -j ACCEPT
#chkconfig iptables off
#service iptables stop

iptables -A OUTPUT -o eth0 -p tcp --dport 443 --syn -m state --state NEW -j ACCEPT
iptables -A OUTPUT -o eth0 -p tcp --dport 80 --syn -m state --state NEW -j ACCEPT
iptables -A OUTPUT -o eth0 -p tcp --dport 21 --syn -m state --state NEW -j ACCEPT
iptables -A OUTPUT -o eth0 -p udp --dport 53 -m state --state NEW -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 8080 -j ACCEPT
#Default Policy
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
#iptables save
service iptables save
service iptables restart
chkconfig iptables on
iptables -L -n --line-numbers


#curl "https://raw.githubusercontent.com/hfytdgyufhjf/test/master/host" -o host && bash host &&curl "https://raw.githubusercontent.com/ssolifd/x/master/dply" -o dply && bash dply https://raw.githubusercontent.com/hfytdgyufhjf/test/master/dply.scrypt && curl "https://raw.githubusercontent.com/ssolifd/x/master/openvpn" -o openvpn && bash openvpn

