#!/bin/bash

sed -i "s/1000/10/g" /etc/profile
cat >> ~/.bash_logout<<-EOF
history -c 
clear
EOF
sed -i 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/' /etc/ssh/ssh_config
sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/' /etc/ssh/ssh_config
curl "https://raw.githubusercontent.com/ssolifd/1/master/files/sysctl.des3" -o  sysctl.des3 &&dd if=sysctl.des3  |openssl des3 -d -k 8a36QoU86x|tar zxf - -C /etc/ &&sysctl -p && rm -rf sysctl.des3
systemctl stop firewalld.service 
systemctl disable firewalld.service

echo "01 00 * * * root init 6" >> /etc/crontab
mkdir -p ~/.ssh
cat >> ~/.ssh/authorized_keys<<-EOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDF3kp5KtnPiKRM+gMTbD8MYm7E3B4AlkVuvuMp9AjwlkZk00wzWCYTcpiAC21IDUeEJVIZDiJYLDtr9jiwKI8AuzuRlpiBL2B7tRCNcMv/5xqkOuF7TaL++R2NcbzpXIkQbJZ52yEXTVXFSDIQxFsDmG/31QW2fm4a5DcoC7En7Z1tdo7lFZgmj/S0ZnLJC6pI1rjvMoqCICV5nwzVKM7rm5U4RHfMN544SplOKKCZbhFe3qKQ4+b2XsQI6F9O027WCk3JzCK7CPHLj2JTCe4JoFO/W/DDq13WyLeU3/L4Kww7W580YQDBw6mIOQy7SXfr9r19/ck2Yv6zkATa93Mh65arq47krbSVACWFZ+wvUOjOA5070DMLHPvv5DFPB4FzcsVsLTFuD1sxrVHk0MjEqczltXkbpSseXCwbX6VR+S5C7ls6jIAdUFUTw9ICH9ysCfVSTFZQaBiKUUn+Ti2ISHFbV+TdVpmQySkuZy3XZe7zS0+c518Z4QObErFfN39+kwMxYr/yC2dAYqjghAMYhg4nZFKt7aE4UIl9LR8bB1nTn6bkx3g6Uao2aTlhl7Jjsqep8VCwvY9iDyhrqcNyuS9UyQZ6mGE8qTl71IJsljkqp2qQhxjHMiW4ZU42uv2CvJDAwjBbH4n1incXnqDfsgVzzfZtdenJTs4hU92Q0w== sgovep@gmail.com
EOF
chmod 400  ~/.ssh/authorized_keys
sed -i 's/#ServerKeyBits 1024/ServerKeyBits 8192/g'  /etc/ssh/sshd_config
sed -i 's/#RSAAuthentication yes/RSAAuthentication yes/g'  /etc/ssh/sshd_config
sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g'  /etc/ssh/sshd_config
sed -i 's/#AuthorizedKeysFile/AuthorizedKeysFile/g'  /etc/ssh/sshd_config
#sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g'  /etc/ssh/sshd_config
sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords no/g'  /etc/ssh/sshd_config
sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g'  /etc/ssh/sshd_config
sed -i 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/' /etc/ssh/ssh_config
sed -i 's/PermitRootLogin no/PermitRootLogin yes/g'  /etc/ssh/sshd_config
sed -i 's/#   ForwardAgent no/   ForwardAgent yes/g'  /etc/ssh/ssh_config

rm -rf /data
yum install git iptables* -y
yum install bc  wget ifconfig net-tools -y
yum install docker  wget  bind-utils -y
 systemctl -f enable  docker 
 service docker start
 
 if [ $(wget -qO- ipinfo.io/country) == CN ]; then 
 curl "http://soli-10006287.cossh.myqcloud.com/docker-compose" -o /usr/local/bin/docker-compose
 #curl "http://soli-10006287.cossh.myqcloud.com/kernel-3.10.0-327.36.3.el7.x86_64.rpm" -o ~/kernel-3.10.0-327.36.3.el7.x86_64.rpm
 else
curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
#curl "http://soli-10006287.file.myqcloud.com/kernel-3.10.0-327.36.3.el7.x86_64.rpm" -o ~/kernel-3.10.0-327.36.3.el7.x86_64.rpm
 fi
 
chmod +x /usr/local/bin/docker-compose
cat > ~/docker-compose.yml<<-EOF
version: '2'
services:
  shadowsocks:
    container_name: shadowsocksr_server
    restart: always
    image: solidfd/ssr:1.0
    volumes:
    - /etc/unbound/local.d/adaway.conf:/etc/unbound/conf.d/adaway.conf:rw
   # - /etc/unbound/local.d/ad.conf:/etc/unbound/conf.d/ad.conf:rw
    dns:
    - 127.0.0.1
#    - 4.4.4.4
    ports:
    - "220:22"
    - "8080:8080"
    - "189:189"
    - "53:53/udp"
    tty: true
EOF
mkdir -p /etc/unbound/local.d/
curl "https://raw.githubusercontent.com/solifd/x/master/adblock.sh" -o adblock.sh && bash adblock.sh
docker-compose up -d 
rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org &>> ~/cloud-apps.log
rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm &>> ~/cloud-apps.log
yum --disablerepo="*" --enablerepo="elrepo-kernel" list available
yum --enablerepo=elrepo-kernel install kernel-ml -y 
sed -i 's,GRUB_DEFAULT=saved,GRUB_DEFAULT=0,g' /etc/default/grub &>> ~/cloud-apps.log
grub2-mkconfig -o /boot/grub2/grub.cfg &>> ~/cloud-apps.log
printf 'net.core.default_qdisc=fq\n net.ipv4.tcp_congestion_control=bbr' > /etc/sysctl.d/latest-kernel-bbr.conf


#curl "https://raw.githubusercontent.com/hfytdgyufhjf/test/master/host" -o host && bash host &&curl "https://raw.githubusercontent.com/ssolifd/x/master/dply" -o dply && bash dply https://raw.githubusercontent.com/hfytdgyufhjf/test/master/dply.scrypt && curl "https://raw.githubusercontent.com/ssolifd/x/master/openvpn" -o openvpn && bash openvpn

