#!/bin/bash

# Block advertisements, malware, and tracking domains using unbound recursive DNS
# Some lists are for personal use only

# Check if running as root
if [ "$(id -u)" != "0" ]; then
  exec sudo "$0" "$@"
fi


# IP address to send traffic
blackHoleDNS="0.0.0.0"
blackHoleDNS6="::"

# Location of configuration file
configurationFile="/tmp/host"
rm -f $configurationFile

# Clean up for refresh
rm -f /tmp/blackhole
rm -f /tmp/blackholedomains
rm -f /tmp/blackholeuniq
rm -f /tmp/blackholeconfig
touch /tmp/blackhole

# Notice for user
echo "Please wait while we gather and install blocking lists..."
curl -s http://pgl.yoyo.org/adservers/serverlist.php? | grep -P '(?=^.{5,254}$)(^(?:(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$)' >> /tmp/blackhole
# Retrieve lists
curl -s http://www.malwaredomainlist.com/hostslist/hosts.txt | grep -v "#" | awk '{print $2}' >> /tmp/blackhole
curl -s http://winhelp2002.mvps.org/hosts.txt | grep -v "#" | awk '{print $2}' | less >> /tmp/blackhole
curl -s http://someonewhocares.org/hosts/hosts | grep -v "#" | awk '{print $2}' >> /tmp/blackhole
curl -s https://hosts-file.net/ad_servers.txt | grep -v "#" | awk '{print $2}' >> /tmp/blackhole
curl -s https://adaway.org/hosts.txt | grep -v "#" | awk '{print $2}' >> /tmp/blackhole
curl -s http://malwaredomains.lehigh.edu/files/justdomains >> /tmp/blackhole
curl -s https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt | grep -v "#" >> /tmp/blackhole
curl -s https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt | grep -v "#" >> /tmp/blackhole
curl -s https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt | grep -v "#" >> /tmp/blackhole
curl -s https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt | grep -v "#" >> /tmp/blackhole
curl -s https://raw.githubusercontent.com/hfytdgyufhjf/test/master/ad | grep -v "#" >> /tmp/blackhole
#cat /home/share/host | grep -v "#" >> /tmp/blackhole
# Sanatize output to only domains in /tmp/blackholedomains
cat /tmp/blackhole | uniq -u > /tmp/blackholeuniq
cat /tmp/blackholeuniq | grep -v "localhost" | grep -v "local" | grep -v "127.0.0.1" | grep -v "::1" > /tmp/blackholedomains
sed -i 's/^ *//; s/ *$//; /^$/d; /^\s*$/d' /tmp/blackholedomains

# Trim and format domains for unbound 
rm -f $configurationFile
for a in `cat /tmp/blackholedomains`; do
                echo ''$blackHoleDNS'    '$a'' >> /tmp/blackholeconfig
done


# Remove carraige return and output configuration file
tr -d '\r' < /tmp/blackholeconfig > $configurationFile


# Cleanup
rm -f /tmp/blackhole
rm -f /tmp/blackholeuniq
rm -f /tmp/blackholeconfig
if [ -s /root/hosts ]; then
echo " /root/hosts [found]"
else
echo "Error:  /root/hosts not found!!!download now......"
cp /etc/hosts /root/hosts
fi
cat /root/hosts >/etc/hosts
cat /tmp/host >> /etc/hosts
# Confirm completion
echo "Installed blocklist and set to update daily"
